# Generated by Django 3.2 on 2021-05-26 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(default='uncategorized', on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Категория'),
        ),
    ]
