# Generated by Django 3.2 on 2021-05-28 09:49

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='header_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[500, 300], upload_to='images/', verbose_name='Изображения'),
        ),
    ]
