# Generated by Django 3.2 on 2021-05-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_articles_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображения'),
        ),
    ]
